nome = str(input('Informe seu nome completo: ')).strip()
print('Análisando seu nome...')
print('Seu nome em letras maiúsculas é {} '.format(nome.upper()))
print('Seu nome em letras minúsculas é {} '.format(nome.lower()))
print('Seu nome tem {} Letras '.format(len(nome)-nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras '.format(separa[0], len(separa[0])))
